# Generated by Django 3.2 on 2024-02-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srn', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=120)),
                ('syear', models.IntegerField(default=1)),
                ('sbranch', models.CharField(choices=[('1', 'CSE'), ('2', 'CSM'), ('3', 'AIML'), ('4', 'Other')], default='1', max_length=5)),
            ],
        ),
    ]
